### ISSUE TITLE
`rename` option documentation

### ISSUE THREAD

**Issue by 0x-r4bbit** [gruntjs/grunt-contrib-copy#118]
I just needed to rename several filename during a grunt-copy with a wildcard pattern. This stackoverflow answer did the trick: http://stackoverflow.com/questions/15271121/how-can-i-rename-files-with-grunt-based-on-the-respective-files-parent-folder

Why isn't the `rename` option documented? Is that intended or is it just not done yet?

**Comment by JKAussieSkater** [comment]
I've written some documentation (with examples) on the rename function. Until my pull request is merged, you can access it [from here] (https://github.com/JKAussieSkater/grunt-docs/blob/rename-doc/Configuring-tasks.md#the-rename-option).
I realise this "issue" is two years old, and you probably know how to rename by now, but this is mainly to help future Googlers 😉
