### ISSUE TITLE
Best way to exclude files?

### ISSUE THREAD

**Issue by yocontra** [gruntjs/grunt-contrib-copy#13]
I want to copy `client/js/**` to `public/js` and exclude all files that end in .coffee - What's the best way to do this?

Right now I'm trying `"./public/js/": ["./client/js/**","!./client/js/*.coffee"]`

**Comment by pixel-streamer** [comment]
this worked for me, to allow copying everything but .json and .js files:
    copy: {
      main: {
        files: [
          { expand: true, src: ['<%= dirs.src %>/*.!(json|js)'], dest: '<%= dirs.dest %>', filter: 'isFile' }
        ]
      }
    },
