### ISSUE TITLE
extra c: added to destination path on windows

### ISSUE THREAD

**Issue by JustinBeckwith** [gruntjs/grunt-contrib-copy#134]
Using the latest version of grunt and grunt-contrib-copy.  I'm trying to create a pretty simple task that just copies a list of files from one location to another:

```
 copy: {
            sdk: {
                files: [
                {
                    expand: true,
                    src: ['myPath/*.js'],
                    dest: 'definitions/',
                    filter: 'isFile'
                }
            ]}
        }
```

When I run the task, I'm getting the following error:

```
Running "copy:sdk" (copy) task
Warning: Unable to create directory "C:\...\mypath\..\definitions\C:" (Error code: ENOENT). Use --force to continue.
```

Notice the bonus \C: at the end of the path.

**Comment by GiladSolter** [comment]
I had the exact same problem, try adding flatten:true and lose the cwd

**Comment by harikishorekuppa** [comment]
I too had the same problem where it got fixed by doing like this 
add your path in cwd but make sure src should be as below '**/*.js' etc.. as well doing only files add filter too
no need to change anything related to dest
copy: {
        main: {

            files: [
                {   expand: true, 
                    cwd : '/dev/war archive/latestfile/'
                    src: ['_**/*.txt_'], 
                    dest: '/fernando/backups/pbuse/war',
                    filter :'isFile' 
                }
            ]

        }   

    }
