### ISSUE TITLE
No test & example doc for noProcess option

### ISSUE THREAD

**Issue by Industrial** [gruntjs/grunt-contrib-copy#141]
I'm not sure it currently works as advertised.

``` coffee
copy:
    options:
        noProcess: ['**/*.less', '**/*.coffee']

    build:
        expand:    true
        cwd:       'src/'
        src:       ['**']
        dest:      'build'
        filter:    'isFile'
```

I'm not sure why noProcess is passed in the options object and not per file entry / build target?

**Comment by shepsii** [comment]
Appreciate this was closed above.

But the docs for noProcess are currently lacking. Most people learn by example. Just one short example would be hugely helpful. Right now, all we have to go on is:

"Type: String This option is passed to grunt.file.copy as an advanced way to control which file contents are processed."

This is a great plugin. I'm very thankful for it. Just respectfully submitting feedback that that's not a sufficient description to be able to use this option and an example would likely be the easiest way of doing that.

Thank you for your consideration!
