### ISSUE TITLE
Add hardLink option to grunt-contrib-copy

### ISSUE THREAD

**Issue by xsellier** [gruntjs/grunt-contrib-copy#146]
I have a build process with grunt that copies a bunch of files (and does some other work). We truly need to preserve hard links.

The idea behind a hardLink option would be hard-link-if-you-can, and on platforms without that option it would do a copy, or copy when a hard link isn't possible (e.g., across devices).

**Comment by oitofelix** [comment]
I just published [grunt-contrib-hardlink](https://github.com/oitofelix/grunt-contrib-hardlink) (initially forked from [grunt-contrib-symlink](https://github.com/gruntjs/grunt-contrib-symlink)) which solves the problem of a recursive hard-linking grunt task.
