### ISSUE TITLE
can I add an option to make it work  in move pattern?

### ISSUE THREAD

**Issue by zhiyelee** [gruntjs/grunt-contrib-copy#178]
can I add an option to make the task work in `move` pattern, like a `mv` option?

When set to true, it perform `mv` file instead of `copy` file

cc @sindresorhus @shama

**Comment by evil-shrike** [comment]
please add moving mode! currently it's hard to find an appropriate plugin right now. There's `grunt-move` (terrible), `grunt-contrib-rename` (terrrible), but actually we just need the same logic as in grunt-contrib-copy but remove files after copying.
