### ISSUE TITLE
Copying from Mac to Win

### ISSUE THREAD

**Issue by rfphill** [gruntjs/grunt-contrib-copy#208]
I've created a copy task that needs to copy from a Mac to a windows server.  

When I specify a destination folder like this 'smb://myServerName/destFolder/', the copy will merely create a local folder called 'smb:' and copy the files there (mimicking the rest of the folder structure above).  In the mac world, that protocol specifier is necessary to mount to a windows path.

If it just didn't recognize the protocol specifier I would expect to see an error, but it actually creates a local 'smb:' folder, which is very puzzling to me.

Note, that when I run the grunt script from a windows box and point the destination folder to '//myServerName/destFolder' it works perfectly fine.

grunt-contrib-copy version: 0.7.0

Thanks,

Ronaldo
(brevity due to frustration and too much IPA)

**Comment by annaocd** [comment]
+1 same thing here. Were you able to find a workaround?

**Comment by rfphill** [comment]
Sadly, no, Anna.  I had to switch gears to another project but will return my attention to it again soon.  If you happen to stumble on a solution let me know.  It's terribly inconvenient!

**Comment by vladikoff** [comment]
> I've created a copy task that needs to copy from a Mac to a windows server.

I would suggest writing a custom task for this specific case. Not sure if `smb://` copy will be supported with this plugin.
