### ISSUE TITLE
Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by log2-hwan** [gruntjs/grunt-contrib-copy#21]
I found error(EMFILE) in copy module when I tried to copy almost 4000 files in 'watch' task.

I guess that this module may open files simultaneously, and it can cause error EMFILE.

It can be my mistake, but please check about situation that copying many file in 'watch' task.

Thank you.

**Comment by epicwhale** [comment]
+1 @leek

**Comment by roNn23** [comment]
+1 @leek

**Comment by nnaelle** [comment]
Did anyone experience any problem after executing @leek 's command? 
My computer crashes after 10-20 mins of grunt use.

**Comment by flatsteve** [comment]
@nnaelle Same issue - Mac Yosemite (10.10.3) hangs after running this command. Did you manage to solve the issue? Cheers.

**Comment by ivancamilov** [comment]
@nnaelle and @flatsteve, perhaps you should set a lower limit, like 1024 or so.

**Comment by jhoniemartinez** [comment]
@flatsteve I'm having the same issue after updating to Yosemite (10.10.3)

**Comment by nnaelle** [comment]
@flatsteve no... I kinda-sorta fixed my gruntfile, but my guess is that it gets stucked on an infinite loop, and as my job was not really related to that and that the gruntfile was made by another company, I chose not to touch it too much and just delete some of the lines that were crashing my computer. (basically I had 3 infinite loops, deleted two, my computer wasn't crashing anymore with just 1 infinite loop, it was just getting reaaaaally slow). Also, using grunt watch just once in a while vs. during all the time I was working on my project helped.

**Comment by vizonluo** [comment]
I find a solution in Yosemite (10.10.3) and it works for me.  see http://problemsolv.in/fix-mac-os-x-yosemite-ulimit-problem/

**Comment by flatsteve** [comment]
@nnaelle Thanks! I also fixed the issue by modifying my grunt file... 
Note to others, if you are seeing this issue it is possible you are watching too many files in your grunt/gulp watch task (make sure you are not being stupid like me and watching the contents of your jspm_packages directory :wink:).

**Comment by alundiak** [comment]
FYI.

`.bash_profile` update didn’t help me for 10.10.3, but reinstallation NodeJS from 0.10.35 to 0.12.3 helped me, and error disappear.

**Comment by rizkysyazuli** [comment]
the `.bash_profile` solution works for me. thx @vizonluo!

**Comment by msikma** [comment]
@leek: please edit your answer, this causes an instant system hang on Yosemite for at least myself and several others in this thread.

**Comment by chuckbuckethead** [comment]
+1 @vizonluo

**Comment by ericmotil** [comment]
:+1:  <code>.bash_profile</code> worked for me too. Thanks, @vizonluo.

**Comment by kmoe** [comment]
Please be careful with @leek's solution. The limit is way too low for many systems and will cause them to hang until reboot. *Do not add these lines to your `bash_profile` or similar until you know the limit is high enough.*

**Comment by leek** [comment]
Thanks @kmoe @msikma - I've edited my comment just in case others come across this thread.

**Comment by dansandland** [comment]
+1 @alundiak - Reinstalling the latest NodeJS resolved it for me. I'm on Yosemite.

**Comment by brennanMKE** [comment]
The solution of the max file limit is different for macOS Sierra. I wrote up instructions which can resolve the problem.

https://gist.github.com/brennanMKE/f6aa55b452ecda2f4c7a379e21647c88
