### ISSUE TITLE
Problem with excluding files.

### ISSUE THREAD

**Issue by harisaamin** [gruntjs/grunt-contrib-copy#215]
This is the array I use in the 'key' of my copy task, which copies my files to the 'Build' folder:

activeProjectFiles = [  '**',
                                '.htaccess',
                                '!\*\*/node_modules/\*\*',
                                '!\*\*/excelsheet/\*\*',
                                '!\*\*/Build/\*\*',
                                '!\*\*/docs/\*\*',
                                '!\*\*/*.ftppass',
                                '!\*\*/package.json',
                                '!\*\*/GruntFile.js',
                                '!\*\*/test/\*\*'
                                ];

Sometimes, I do want to copy the test folder into my 'Build' folder, and for that I REMOVE the '!' operator making it:

activeProjectFiles = [  '**',
                                '.htaccess',
                                '!\*\*/node_modules/\*\*',
                                '!\*\*/excelsheet/\*\*',
                                '!\*\*/Build/\*\*',
                                '!\*\*/docs/\*\*',
                                '!\*\*/*.ftppass',
                                '!\*\*/package.json',
                                '!\*\*/GruntFile.js',
                                '\*\*/test/\*\*'
                                ];

When I do this, it copies the node_modules folder too, which is marked with the '!' operator for NOT copying. When I change the location of "'\*\*/test/\*\*'" in the array, making it:

activeProjectFiles = [  '**',
                                '.htaccess',
                                '\*\*/test/\*\*',
                                '!\*\*/node_modules/\*\*',
                                '!\*\*/excelsheet/\*\*',
                                '!\*\*/Build/\*\*',
                                '!\*\*/docs/\*\*',
                                '!\*\*/*.ftppass',
                                '!\*\*/package.json',
                                '!\*\*/GruntFile.js'
                                
                                ];

.. it works just fine.

Could anyone guide me as to why this is happening? Is it necessary to keep all '!' files after the files which I want to copy? Is the order important? The order should technically not be important.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
