### ISSUE TITLE
Not copying empty dirs

### ISSUE THREAD

**Issue by publicJorn** [gruntjs/grunt-contrib-copy#22]
Hiya,
I'd like my dist dir to have two empty directories, so the future users of my project know that additional files can be placed there. I thought of providing 2 empty dirs in the source dir and copy them to the dist dir, since I couldn't find a "create dir" plugin for gruntjs and I like this copy plugin :)

I get the error: Unable to copy; no valid source files were found. Use --force to continue. 
I'm using Windows.

folder structure:

``` javascript
sjaak/
  dist
  src/
    modules (empty dir to be copied)
    utils (empty dir to be copied)
    core/
      (src core files)
    (src files)
```

Excerpt of grunt.js file:

``` javascript
...
copy: {
  dist: {
    files: {
      'dist/': 'src/modules' // For now just /modules/ to test
    }
  }
}
..
```

This issue was also addressed in: https://github.com/gruntjs/grunt-contrib/issues/103
There it was noted that this issue was fixed, but to me it seems it's not.

**Comment by mojoaxel** [comment]
This feature has been removed with bffcef8680ead762f32b3bbd6bc0472b03f35640
