### ISSUE TITLE
Question: Selective Copies

### ISSUE THREAD

**Issue by KDCinfo** [gruntjs/grunt-contrib-copy#230]
Hi there, 

Sorry if this is the wrong place, but couldn't find another place (other than the empty Wiki) to ask a question. Was wondering if you can set this up to do selective copies? Say, if one task wanted to target some files for copying, while another task may want to target others. 

Thanks in advance. 

-Keith

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by KDCinfo** [comment]
Hi there, Unsure if you meant copy this page into my question on SO, or link my SO question into this (closed) issue. In any case, I'm doing both :) Thanks! (...and thank you for this great tool!).

http://stackoverflow.com/questions/29887775/grunt-contrib-copy-multiple-copy-tasks
