### ISSUE TITLE
copy exclude files in .gitignore

### ISSUE THREAD

**Issue by przemyslawpluta** [gruntjs/grunt-contrib-copy#231]
Is there a way to copy `src` directory into `dest` directory without files and folders present in `.gitignore`? Thanks.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by HardeepAsrani** [comment]
I know it's very late but just leaving here if anyone in future is looking for this. We've done something similar using the `ignore` package: https://github.com/Codeinwp/grunt-plugin-fleet/blob/master/grunt/copy.js
