### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Dev-Dipesh** [gruntjs/grunt-contrib-copy#247]
I've tried to copy my library files several times in all possible way, but don't know why it's going in an infinite loop:

```
copy: {
      fonts: {
        expand: true,
        src: 'source/fonts/*',
        dest: 'dist/'
      },
      img: {
        expand: true,
        src: 'source/img/*',
        dest: 'dist/'
      },
      js: {
        expand: true,
        cwd: 'dist/',
        src: [
          'source/js/vendor/**/*',
          'source/js/lib/**/*',
          'source/js/lib/*'
        ],
        dest: 'dist/js'
      },
      css: {
        expand: true,
        cwd: 'dist/',
        src: [
          'source/css/vendor/**/*'
        ],
        dest: 'dist/css/*'
      }
    },
```

```
grunt.registerTask('copy', ['copy:fonts', 'copy:img', 'copy:css', 'copy:js']);
```

When I run this without verbose then there is not a single line to show, however when I used verbose it showed me infinite loop with nothing copied.

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

Running "copy:fonts" (copy) task

-----------------------------------------

**Comment by vladikoff** [comment]
http://gruntjs.com/frequently-asked-questions#why-am-i-getting-a-maximum-call-stack-size-exceeded-error

**Comment by Dev-Dipesh** [comment]
Thanks for pointing out, but that's not the case. I've specifically registered a task only for all copy operations so there is no other place I've defined it again.

**Comment by vladikoff** [comment]
@Dev-Dipesh could you rename `copy` alias to `myCopy`, does it still loop?

**Comment by Dev-Dipesh** [comment]
Yes! I've already tried that option too.

You can check my `Gruntfile` here

https://www.dropbox.com/s/10ih5ijwhok464s/Gruntfile.js?dl=0

**Comment by Dev-Dipesh** [comment]
Allright I only have to rename the copy at registerTask, my bad I previously renamed even the definition one which changes the whole module name.
It's resolved now!
