### ISSUE TITLE
Chalk dependency issue

### ISSUE THREAD

**Issue by alexbeletsky** [gruntjs/grunt-contrib-copy#251]
There is an issue with one of dependencies, namely https://github.com/chalk/chalk/pull/81

npm published version v0.8.0 depends on `"chalk": "^0.5.1"` which still contains the bug and brakes current build pipeline. In master, it already fixed to `"chalk": "^1.0.0"`. 

If it can be back-ported and package is re-published, that would be just awesome.

**Comment by sindresorhus** [comment]
Done.
