### ISSUE TITLE
We need a documented example for copying without full path

### ISSUE THREAD

**Issue by ybdesire** [gruntjs/grunt-contrib-copy#256]
I and a lot of people need to get a copied structure as below. But there is no such document.
```
.
├── Gruntfile.js
├── dest
│   ├── a
│   └── subdir
│      └── b
└── src
    ├── a
    └── subdir
        └── b
```
If we provide an example at the document, the following questions will be resolved. BTW, there is people at stackoverflow showed the desire for such example and document enhancement.

1. http://stackoverflow.com/questions/19297067/how-to-copy-files-without-the-full-path-with-grunt-js

2. http://stackoverflow.com/questions/23875740/grunt-contrib-copy-files-are-not-copied-to-the-correct-locaiton?lq=1

3. http://stackoverflow.com/questions/23655499/copy-files-but-lose-folder-structure?rq=1

I can provide the pull request for readme.md modification if you like.

**Comment by ricog** [comment]
There is an example of using `cwd` in the `README.md`.
https://github.com/gruntjs/grunt-contrib-copy/blob/master/README.md#usage-examples

For reference, here is an example of what you would need for the above folder structure.

```js
copy: {
  main: {
    expand: true,
    cwd: 'src',
    src: ['**'],
    dest: 'dest/'
  }
}
```

**Comment by ybdesire** [comment]
Yes, we already have the cwd using example at README.md. But currently the description is not very clear, so I think it's better if we can highlight an independent example for "copying without full path".

**Comment by vmadman** [comment]
Yeah... thankfully I found this issue while I still had a little hair left.

If you're copying files from `src/` to `dist/` .. it would seem like the most common use case would not expect a directory named `dist/src/`.  You would, instead, want `src/*` -> `dist/*`.

I definitely think this should be added to the core docs.

**Comment by arturmamedov** [comment]
Documentation aren't clear, or i am a dumb, and it would be cool if documentation can explain also to dumb people how to copy with grunt, from one src/* to another dest/ directory all the files, without any other sub dir and things. Thanks!

**Comment by ricog** [comment]
@arturmamedov What helped me the most was reading Grunt's [Configuring tasks](https://gruntjs.com/configuring-tasks) doc, especially the [Files](https://gruntjs.com/configuring-tasks#files) section. Based on your request, it seems your use case would be satisfied by the first example. To copy only files from `src` to `dest`.

```
copy: {
  main: {
    files: [
      // includes files within path
      {expand: true, src: ['src/*'], dest: 'dest/', filter: 'isFile'},
    ],
  },
},```

I encourage you to submit a PR if you see an opportunity to clarify the documentation.
