### ISSUE TITLE
Does not work with grunt-newer due to the timestamp precision disagreement

### ISSUE THREAD

**Issue by Determinant** [gruntjs/grunt-contrib-copy#257]
As I tried, when specify newer:copy, the files will be copied no matter whether it gets modified. As I have observed, grunt-contrib-copy uses `fs.utimesSync(dest, stat.atime, stat.mtime);` to sync the timestamp, which only gives second-level precision (can be reproduced by first using grunt-contrib-copy to copy the file and then stat the original file and the copied version to see). And I think grunt-newer uses more strict comparison which based on the millisecond-level precision. I don't know this should be either a bug or a feature enhancement for either package, but it would be great if they can work together.

**Comment by XhmikosR** [comment]
These failures are reflected in tests. https://travis-ci.org/gruntjs/grunt-contrib-copy

If anyone can make a PR please CC me.

**Comment by parkersweb** [comment]
Cross posting the discussion from the same thread from newer...

https://github.com/tschaub/grunt-newer/issues/86

**Comment by nalajcie** [comment]
Just created a pull request resolving this issue:  https://github.com/gruntjs/grunt-contrib-copy/pull/268

**Comment by mscarchilli** [comment]
I have a custom watch task that can handle it. I use this with packages that don't play nice with grunt-contrib-newer. Feel free to use it and adjust to your needs.

**My paths**
```
    path: {
      dev: {
        base: "dev"
      },
      dist: {
        base: "./dist"
      },
    },
```
**Copy task**
```
    copy: {
      main : {
        expand: true,
        flatten: true,
        src: ["<%= currentFullFilePath %>"],
        dest: "<%= path.dist.base %><%= currentFilePath %>",
        filter: "isFile"
      },
    },
```
**Watch Task**
```
    watch: {
      html: {
        files: ["<%= path.dev.base %>/**/*.html"],
      },
    },
```
**Custom Watch Event**
```
  grunt.event.on("watch", function (action, filePath) {
    var file          = filePath.replace(/^.*[\\\/]/, "");
    var thisFileParts = file.split(".");
    var fileName      = thisFileParts[0];
    var fileExtension = thisFileParts.pop();
    var filePathClean = filePath.substring(filePath.indexOf(/dev\\views/) + 10);
    filePathClean     = filePathClean.replace(file, "");

    grunt.config.set("currentFullFilePath", filePath);
    grunt.config.set("currentFilePath", filePathClean);

    if (fileExtension == "html") {
      grunt.task.run("copy:main:[" + fileName + "]");
    }
  });
```
