### ISSUE TITLE
how can we get the total time when we finish a copy task?

### ISSUE THREAD

**Issue by butian** [gruntjs/grunt-contrib-copy#263]
Although we know grunt can finish a copy task very soon, how can we output the total time when it finishes? Maybe we can add an optional parameter?

Here I just add the code in copy.js (line 95) to achieve it:

<code>
 grunt.registerMultiTask('copy', 'Copy files.', function() {  
  
 var startTime = new Date();  

...  
...

grunt.log.writeln();

var finishTime = new Date();

grunt.log.write('It takes ' + (Date.parse(finishTime) - Date.parse(startTime))/1000 + ' seconds to finish the copy task');
</code>

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by sindresorhus** [comment]
`$ time grunt copy` or https://github.com/sindresorhus/time-grunt
