### ISSUE TITLE
Incompatible with grunt 1.0.1

### ISSUE THREAD

**Issue by scvandenbraak** [gruntjs/grunt-contrib-copy#280]
It doesn't seem like the plugin is compatible with grunt 1.0.1. I get errors like:

```
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-copy@0.1.0 wants grunt@~0.4.2
```

See http://gruntjs.com/upgrading-from-0.4-to-1.0

**Comment by vladikoff** [comment]
` grunt-copy` !== `gruntjs/grunt-contrib-copy`

**Comment by scvandenbraak** [comment]
I was sure I tried both, but thanks for the quick reply. This pointed out my mistake (probably wrong copy/paste second time), so I just ran `npm install grunt-contrib-copy --save-dev` and it works like perfectly!

**Comment by scvandenbraak** [comment]
I now know what went wrong. I works now, but I just wanted to let you know. If you try to install grunt-copy first and get the errors, it places a grunt-copy directory in your node_modules directory. If you then try to install `npm install grunt-contrib-copy --save-dev` you get the error in my first post. It only works after you delete the original grunt-copy directory from node_modules because of the failed install of that. That's why I got the above error when trying to install this module.
