### ISSUE TITLE
syncTimestamp running even if timestamp option is false

### ISSUE THREAD

**Issue by SystemDisc** [gruntjs/grunt-contrib-copy#287]
My timestamp option is not set, so it should be `false`. However, `syncTimestamp` is being called, which results in a `Warning: EPERM: operation not permitted, futime Use --force to continue.` since the user running `grunt` does not own the destination files, but is a member of the same group as the owning users and has write access.

**Comment by relaxatorium** [comment]
Seeing the same issue, unless I misunderstand the code it seems pretty easy to fix so creating a quick pull request.

**Comment by relaxatorium** [comment]
Okay, I don't actually have the time to do this at work given that a CLA needs to be signed and tests need to be written, etc., but I believe the issue is the following:

line 100

```
syncTimestamp(src, dest);
```

needs to be wrapped in an option check like so

```
if (options.timestamp !== false) {
  syncTimestamp(src, dest);
}
```

That fixed the error in my quick testing/debugging
