### ISSUE TITLE
Copy task not working in  windows running forever

### ISSUE THREAD

**Issue by tamimibrahim17** [gruntjs/grunt-contrib-copy#295]
```
var grunt = require('grunt');
grunt.initConfig({
	copy : {
		main : {
                        expand: true,
			src : 'test/**',
			dest : 'hola/'
		},
	}
});
grunt.loadNpmTasks('grunt-contrib-copy');
grunt.registerTask('copy','copy');
```
this is grunt.js file. What I am doing is just copying few test files from one directory to another. when I run grunt copy in commandline, I get this output
```
$ grunt copy --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-contrib-copy" local Npm module tasks.
Reading D:\workcode\node_modules\grunt-contrib-copy\package.json...OK
Parsing D:\workcode\node_modules\grunt-contrib-copy\package.json...OK
Loading "copy.js" tasks...OK
+ copy
Loading "Gruntfile.js" tasks...OK
+ copy

Running tasks: copy

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task

Running "copy" task
```
and then grunt `Running "copy" task` run forever but no files or folder being copied. 
I am using windows and `cygwin` console. I have tried some of other examples from readme file but none of these are working.

**Comment by SOHOIT** [comment]
I'm experiencing the exact same issue running grunt via PowerShell or cmd.

**Comment by tamimibrahim17** [comment]
Can anybody help us, about this issue?

**Comment by tripflex** [comment]
Having this same problem on OSX El Capitan using latest version

**Comment by tripflex** [comment]
@SOHOIT @tamimibrahim17

SOOOO ... i feel like a complete idiot, but this is actually our own fault ... we should not be defining a task as `copy` since that's the task already created by the module.

So remove this:
`grunt.registerTask('copy','copy');`

or change it to something like:
`grunt.registerTask('docopy','copy');`

And you will see it starts to work again ... derpppp

**Comment by Zacklane** [comment]
OMG, you're awesome, man!!! Tnx! Spend a half of a day, and you're tip with the naming saved me a lot of time!
