### ISSUE TITLE
Xgboost and Bayesian Optimization

### ISSUE THREAD

**Issue by mfavaits** [gruntjs/grunt-contrib-copy#303]
I am trying to use Bayes Optimization for parameter tuning. Based on examples that I found online I wrote this piece of code:

model = XGBClassifier(n_jobs=-1)

def xgboostcv(eta, n_estimators):
    return np.mean(cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy'))
    
xgboostBO = BayesianOptimization(xgboostcv,
                                 {'eta': (0.01, 0.3),
                                  'n_estimators': (50,500)
                                  })

xgboostBO.maximize(init_points=3, n_iter=5, acq='ei')
print('-'*53)
print(xgboostBO.res['max'])
print(xgboostBO.res['all'])

The program seems to work but last 2 lines give me following TypeError                                 

Traceback (most recent call last)
<ipython-input-28-4c03b552ef6b> in <module>()
     10 xgboostBO.maximize(init_points=3, n_iter=5, acq='ei')
     11 print('-'*53)
---> 12 print(xgboostBO.res['max'])
     13 print(xgboostBO.res['all'])

**TypeError**: **list indices must be integers or slices, not str**

Cannot find what I did wrong and plenty of code online uses exactly the same piece of code

**Comment by mfavaits** [comment]
Closed

**Comment by jarrettyeo** [comment]
You probably are using a newer version of `bayesian-optimization`, and the API is now different for you compared to the older ones used online. Here is some code which you can explore to get the same result:

1. To get the best params:

```
best_params = max(xgboostBO.res, key=lambda x:x['target'])['params']
print(best_params)
```

2. To get a list of all params:

```
all_params = [x['params'] for x in xgboostBO.res]
print(all_params)
```
