### ISSUE TITLE
Copy files to absolute path

### ISSUE THREAD

**Issue by fpinzn** [gruntjs/grunt-contrib-copy#47]
Sorry If I'm missing something, but I'm trying to copy some files inside the project to a subfolder of my home directory.

The configuration in the grunt.js looks like this:

```
copy: {
        main: {
          files: [
            {
              src: ['temp/plugins/**'],
              dest: '~/Library/Application\ Support/sketch/Plugins/',
            }
          ]
        }
      }
```

It creates a subfolder ~ and copies the whole thing there.

**Comment by stereoplegic** [comment]
@ctalkington - that's a nice cross-platform solution. I'll be adding it to the grunt-panda (pandoc) function in my assemble build script so that my resume.md page can be converted to both HTML and DOCX, with the latter sent to my Google Drive folder for syncing.
