### ISSUE TITLE
copy files to different directory

### ISSUE THREAD

**Issue by ghost** [gruntjs/grunt-contrib-copy#58]
Hello,

I am trying to watch and copy the files to different directory if there's any change to the files. I've tried different combinations/options but still can't get only the files to new directory.

watch directory: src/html/*
new directory: build/html/

The best result I can get is: src/html/build/html/some-files.html

I also tried to give cwd the path (src/html) with the src:"*", but the result is a copy of every files and subdirs of the project root.

I've been googling and going through forums but still can't find an answer to my problem.

Your help is greatly appreciated,

Niusaul

**Comment by vgrinko** [comment]
@tkellen very helpful, thank you!
