### ISSUE TITLE
Copy an file into multiple directories

### ISSUE THREAD

**Issue by nielswijers** [gruntjs/grunt-contrib-copy#65]
Is there a way to copy one file into multiple directories.

eg. look at this structure
- build
  - index.html
- dist
  - folder1
  - folder2
  - folder3

i would like to copy the index.html in each folder in dist. the names and the number of the folders in dist can vary.

i've tried to make de dest folder dynamic like this, but then it creates a folder "*"

``` javascript
files:[{
  expand: true,
  cwd: 'build/',
  src: ['index.html'],
  dest: 'dist/*/'
}]
```

thx in advance ;)

**Comment by arnaudleyder** [comment]
+1, unless there is something technically preventing this from happening, dest should support array

**Comment by stopachka** [comment]
+1

**Comment by Blueblau** [comment]
+1

**Comment by dewezlopez** [comment]
+1

**Comment by Miw0** [comment]
+1

**Comment by jackphel** [comment]
+1

**Comment by iKlancar** [comment]
+1

**Comment by ignlg** [comment]
I use a simple function (real example):

```coffee
  platforms = [
    "app/platforms/android/assets/www/"
    "app/platforms/ios/www/"
    "app/platforms/browser/www/"
  ]

  multiCopy = (file, srcDir, dests) ->
    dests.map (dest) ->
      src: "#{srcDir}#{file}"
      dest: "#{dest}#{file}"

  js = multiCopy "main.js", "dist/", platforms
  css = multiCopy "style.css", "dist/", platforms

  @config "copy",
    cordovaJs:
      files: js
    cordovaCss:
      files: css
```

No über-efficient but no need for extra modules. Hope it helps :smiley:

**Comment by jamescookie** [comment]
It would be good to have this feature, but in the meantime, we give 'dest' as an array, and then modify it afterwards:

    grunt.initConfig({
        ...
        copy: {
            main: {
                files: [{
                    src: 'src/html/templates/template.html',
                    dest: ['dist/place/index.html', 'dist/stuff/index.html', 'dist/things/index.html']
                }]
            }
        },
        ...
    });

    var gruntCopy = grunt.config.get('copy');
    for (var item in gruntCopy) {
        var files = gruntCopy[item].files;
        for (var i = files.length - 1; i >= 0; i--) {
            var fileItem = files[i];
            if (fileItem.dest instanceof Array) {
                files.splice(i, 1);
                for (var j = 0; j < fileItem.dest.length; j++) {
                    files.push({src: fileItem.src, dest: fileItem.dest[j]})
                }
            }
        }
    }
    grunt.config.set('copy', gruntCopy);

**Comment by kennysong** [comment]
+1

**Comment by JohnCashmore** [comment]
+1

**Comment by adrianparr** [comment]
+1

**Comment by chris31389** [comment]
+1

**Comment by bertuz** [comment]
+1

**Comment by poisa** [comment]
+1

**Comment by c-eliasson** [comment]
+1

**Comment by sylvainpolletvillard** [comment]
+1

**Comment by gnomesoftuk** [comment]
Yes, this would be very useful +1

**Comment by PhilippSchreiber** [comment]
+1

**Comment by JohnCashmore** [comment]
Problem with this is its something thats hardcoded into grunt task runner the dest value can only be a string, its very simple to change the plugin to deal with arrays.

**Comment by WilcoFiers** [comment]
+1

**Comment by Norreman** [comment]
+1

**Comment by andrewagga** [comment]
+1

**Comment by szjanikowski** [comment]
+1

**Comment by coxrichuk** [comment]
+1

**Comment by beard86** [comment]
+1

**Comment by joaopaschoal** [comment]
+1

**Comment by BB-000** [comment]
+1

**Comment by jayrom** [comment]
+1

**Comment by eltuza** [comment]
+1

**Comment by jpodpro** [comment]
+1

**Comment by rvalitov** [comment]
The solution specified by @jamescookie is great, but it does not respect the options specified by user, for example `dot`, `cwd`, `filter`, etc. For example in my case below the options were ignored:

```js
copy: {
index_root: {
                files: [
                    {
                        expand: true,
                        dot: true,
                        cwd: 'assets/index/root/',
                        src: [
                            '.htaccess',
                        ],
                        filter: 'isFile',
                        dest: ['dist/src/'],
                    },
                ],
            }
}
```

Below is the modified code that correctly processes the options:

```js
const gruntCopy = grunt.config.get('copy');
    for (const item in gruntCopy) {
        const files = gruntCopy[item].files;
        for (let i = files.length - 1; i >= 0; i--) {
            const fileItem = files[i];
            if (fileItem.dest instanceof Array) {
                files.splice(i, 1);
                for (let j = 0; j < fileItem.dest.length; j++) {
                    let s = Object.assign({}, fileItem);
                    s.dest = fileItem.dest[j];
                    files.push(s);
                }
            }
        }
    }
```
