### ISSUE TITLE
Grunt Contrib Copy does not copy .htaccess files on Windows

### ISSUE THREAD

**Issue by CMCDragonkai** [gruntjs/grunt-contrib-copy#70]
Hello, I just tried doing a straight copy with a filter function that doesn't filter out anything.

It does not copy any files that only have a "." as its name.

Such as:

".htaccess"
".git"
".gitignore"

This is a bug? Is there anyway to solve this?

**Comment by PC108** [comment]
I add dot: true to copy all .* files (including .htaccess. It workd for me.
`copy: {
			build: {
				expand: true,
				cwd: 'source/',
				src: ['**'],
				dot: true, /* pour copier le .htaccess */
				dest: 'build/',
			},`
