### ISSUE TITLE
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.

### ISSUE THREAD

**Issue by danyeah** [gruntjs/grunt-contrib-copy#88]
> ```
>       copy: {
>           files: [
>               {
>               expand: true, 
>               src: ['index.html'], 
>               dest: 'deploy/', 
>               filter: 'isFile'
>               } 
>           ]
>       }
> ```
> 
> When i run **grunt copy** i get:
> Warning: Object #<Object> has no method 'indexOf' Use --force to continue.

Any idea why i get this error?

**Comment by prabhap** [comment]
+1. Missed to add 'target' key

**Comment by MushrChun** [comment]
newbie to grunt, same problem, solved by this thread Thx Guys
