### ISSUE TITLE
Unable to read file (Error code: ENOENT)

### ISSUE THREAD

**Issue by tobias-reinhardt** [gruntjs/grunt-contrib-copy#90]
Hi,

since I'm very to new to Grunt I'm sure the problem here is on my side, but I simply can't figure it out. Here's my directory structure:

```
.
├── _build
    └── Gruntfile.js
└── css
    ├── img
    └── src
        └── images
            ├── img-01.jpg
            └── img-02.jpg
```

I now want all the images from `./css/src/images` to be copied to `./css/img`. I think the closest I got was using this code:

``` js
copy: {
        main: {
            expand: true,
            files: [
                {
                    cwd: '../css/src/images/',
                    src: ['**'],
                    dest: '../css/img'
                }
            ]
        }
 }
```

Which resulted in the `--verbose` output:

```
Running "copy:main" (copy) task
Verifying property copy.main exists in config...OK
Files: , img-01.jpg, img-02.jpg -> ../css/img
Options: processContent=false, processContentExclude=[]
Creating ../css/img
Copying img-01.jpg -> ../css/img
Reading img-01.jpg...ERROR
Warning: Unable to read "img-01.jpg" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

The file `img-01.jpg` is obviously there so I don't really get the error message. Can anyone give me a hint here?

Thanks in advance, Tobi

**Comment by devmanhinton** [comment]
Just wanted to add that this idiosyncrasy cost me a bit of time and almost made me look for other grunt add-ons. Can I ask that README is updated with this fact ie., `cwd:'path/'` only works w/  `expand:true`?

Thanks!

**Comment by AkhilGS** [comment]
I faced the same issue when my image file was actually a shortcut. It worked when I copied the original file.

**Comment by franz-josef-kaiser** [comment]
@AkhilGS By _shortcut_, you actually mean _Symlink_?

**Comment by AkhilGS** [comment]
@franz-josef-kaiser Yes, _Symlink_.
